FROM mcr.microsoft.com/devcontainers/base:ubuntu

# Update package list and install necessary packages
RUN apt update && \
    apt install -y \
    wget \
    curl \
    unzip \
    python3 \
    python3-dev \
    python3-pip \
    python3-venv